[package]
name = "tmux-loader"
authors = ["Christopher Giroir <kelsin@valefor.com>"]
description = "A small cli utility for managing tmux sessions"
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.53"
deepmerge = "0.1.0"
etcetera = "0.11.0"
